version: "3.5"

services:
  frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    image: ml-kurkkumopo-frontend
    ports:
      - 3000:3000

  backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    image: ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model

  training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    image: ml-kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - model:/src/model

volumes:
  imgs:
  model:
