version: "3.5"

services:
  redis_db:
    image: redis
    ports:
      - 6379:6379
    container_name: redis_db

  backend:
    image: yuheem98/example-backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis_db

  frontend:
    image: yuheem98/example-frontend
    ports:
      - 5000:5000
