# Base image
FROM ubuntu:latest

EXPOSE 5000

WORKDIR /usr/src/app 

# Install dependencies
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt install -y nodejs

COPY ./example-frontend .

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

RUN npm install
RUN npm run build
RUN npm install -g serve

CMD ["serve", "-s", "-l", "5000", "build"]